version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - db-data:/app/data
      - uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

volumes:
  db-data:
  uploads:
